name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # 从tag获取版本号，去掉v前缀
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "is_tag=true" >> $GITHUB_OUTPUT
        else
          # main分支使用dev版本号
          VERSION="dev-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
          echo "is_tag=false" >> $GITHUB_OUTPUT
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          APP_VERSION=${{ steps.version.outputs.version }}
          WEBSITE_ID=${{ secrets.WEBSITE_ID }}
        tags: ${{ steps.version.outputs.is_tag == 'true' && format('ellermister/mybili:latest,ellermister/mybili:{0}', steps.version.outputs.version) || 'ellermister/mybili:latest' }}
